package c.b.a.a.d.k.o;

import c.b.a.a.d.k.f;
import c.b.a.a.d.k.i;
import c.b.a.a.d.k.j;
import c.b.a.a.d.k.l;
import c.b.a.a.d.k.m;
import java.util.concurrent.TimeUnit;

public final class f0<R extends i> extends f<R> {
    @Override // c.b.a.a.d.k.f
    public final void addStatusListener(f.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final R await(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final void setResultCallback(j<? super R> jVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final void setResultCallback(j<? super R> jVar, long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // c.b.a.a.d.k.f
    public final <S extends i> m<S> then(l<? super R, ? extends S> lVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
